In [1]:
from astropy.table import QTable
from astropy.io import fits
from scipy.interpolate import interp1d
import numpy as np
import mceh.find_luminosity as fl
import tqdm
from importlib import reload
import astropy.units as u

mceh version: 6.0.0-alpha


In [24]:
reload(fl)

<module 'mceh.find_luminosity' from '/home/hylin/workspace/mceh/find_luminosity.py'>

In [3]:
original_efeds = QTable.read('data/modified_efeds_ver9.fits')
hsc = QTable.read('data/modified_hsc_ver5.fits')
rd = QTable.read('data/modified_random_ver3.fits')

In [4]:
original_efeds.colnames

['Name',
 'ID_SRC',
 'RA_CORR',
 'DEC_CORR',
 'Z_BEST_COMB',
 'low_cont_flag',
 'median_500c_lcdm',
 'r500c_lcdm',
 'area',
 'unmasked_area',
 'i_cmag',
 'g_cmag',
 'r_cmag',
 'z_cmag',
 'y_cmag',
 'galaxy_index',
 'unmasked_fraction',
 'SIGMA_Z_BEST_COMB']

In [ ]:
# The columns that need to be changed is unmasked_area, grizy_cmag, galaxy_index, unmasked_fraction

In [5]:
galaxy_index = []
for i in range(len(original_efeds)):
    galaxy_index.append(fl.index_within_angular_radius(hsc['ra'], hsc['dec'], 
                                   original_efeds['RA_CORR'][i], 
                                   original_efeds['DEC_CORR'][i], 
                                   original_efeds['r500c_lcdm'][i]))
    print(f'Finish {i+1}/{len(original_efeds)}')

Finish 1/542
Finish 2/542
Finish 3/542
Finish 4/542
Finish 5/542
Finish 6/542
Finish 7/542
Finish 8/542
Finish 9/542
Finish 10/542
Finish 11/542
Finish 12/542
Finish 13/542
Finish 14/542
Finish 15/542
Finish 16/542
Finish 17/542
Finish 18/542
Finish 19/542
Finish 20/542
Finish 21/542
Finish 22/542
Finish 23/542
Finish 24/542
Finish 25/542
Finish 26/542
Finish 27/542
Finish 28/542
Finish 29/542
Finish 30/542
Finish 31/542
Finish 32/542
Finish 33/542
Finish 34/542
Finish 35/542
Finish 36/542
Finish 37/542
Finish 38/542
Finish 39/542
Finish 40/542
Finish 41/542
Finish 42/542
Finish 43/542
Finish 44/542
Finish 45/542
Finish 46/542
Finish 47/542
Finish 48/542
Finish 49/542
Finish 50/542
Finish 51/542
Finish 52/542
Finish 53/542
Finish 54/542
Finish 55/542
Finish 56/542
Finish 57/542
Finish 58/542
Finish 59/542
Finish 60/542
Finish 61/542
Finish 62/542
Finish 63/542
Finish 64/542
Finish 65/542
Finish 66/542
Finish 67/542
Finish 68/542
Finish 69/542
Finish 70/542
Finish 71/542
Finish 72/542
F

In [6]:
galaxy_index

[array([17128984, 17128991, 17128993, ..., 17172982, 17172983, 17172984]),
 array([36962, 36964, 36965, 36977, 36979, 36980, 36981, 36985, 36987,
        36989, 36991, 36992, 37000, 37002, 37006, 37008, 37010, 37011,
        37012, 37016, 37018, 37023, 37027, 37055, 37058, 37060, 37063,
        37064, 37065, 37070, 37078, 37082, 37087, 37089, 37090, 37093,
        37095, 37096, 37097, 37100, 37102, 37104, 37117, 37120, 37121,
        37125, 37133, 37137, 37138, 37144, 37145, 37149, 37151, 37153,
        37155, 37158, 37161, 37162, 37167, 37168, 37169, 37178, 37180,
        37181, 37182, 37183, 37186, 37189, 37193, 37197, 37199, 37207,
        37209, 37211, 37222, 37223, 37224, 37226, 37228, 37230, 37237,
        37239, 37241, 37243, 37244, 37245, 37246, 37252, 37253, 37254,
        37257, 37258, 37261, 37263, 37267, 37271, 37274, 37276, 37277,
        37278, 37280, 37281, 37283, 37284, 37285, 37287, 37288, 37296,
        37298, 37300, 37303, 37305, 37306, 37309, 37310, 37312, 37313,
  

In [7]:
all_umarea = []
for i in tqdm.trange(len(original_efeds)):
    all_umarea.append(fl.unmasked_area(original_efeds['RA_CORR'][i], original_efeds['DEC_CORR'][i], original_efeds['r500c_lcdm'][i], rd))

100%|██████████| 542/542 [00:52<00:00, 10.34it/s]


In [8]:
all_umarea = [i.value for i in all_umarea] * u.arcmin**2

In [9]:
all_umarea

<Quantity [1.77200e+01, 1.39100e+01, 1.99300e+01, 3.71400e+01, 8.56200e+01,
           1.22500e+01, 3.31400e+01, 1.09726e+03, 4.20900e+01, 3.43500e+01,
           1.15300e+01, 3.94100e+01, 1.19500e+01, 2.01030e+02, 4.95100e+01,
           2.54500e+01, 2.35400e+01, 8.53400e+01, 1.93700e+01, 2.06300e+01,
           4.49700e+01, 4.89700e+01, 3.98000e+01, 2.87100e+01, 2.64400e+01,
           6.20000e+00, 2.33400e+01, 3.20200e+01, 2.06300e+01, 3.78100e+01,
           2.27700e+01, 3.84800e+01, 1.23100e+01, 0.00000e+00, 1.49100e+01,
           0.00000e+00, 7.60000e+00, 2.15800e+01, 3.79700e+01, 1.83000e+01,
           3.12600e+01, 1.84800e+01, 2.01400e+01, 1.89800e+01, 7.48000e+00,
           0.00000e+00, 1.61300e+01, 2.95500e+01, 2.02900e+01, 3.18700e+01,
           5.35000e+00, 1.57000e+01, 2.26700e+01, 3.05900e+01, 1.45400e+01,
           4.69600e+01, 1.16510e+02, 7.55000e+00, 1.42500e+01, 1.39100e+01,
           2.24800e+01, 1.69500e+01, 2.34300e+01, 5.69000e+00, 2.82500e+01,
           1

In [10]:
unmasked_fraction = (all_umarea / original_efeds['area']).value
unmasked_fraction

array([0.84506686, 0.53558189, 0.75017513, 0.86992125, 0.8676326 ,
       0.36474171, 0.8375073 , 0.78121202, 0.57506673, 0.56227303,
       0.89395766, 0.88643441, 0.7671372 , 0.76006707, 0.8694203 ,
       0.88122267, 0.8267037 , 0.68459502, 0.69926892, 0.36006583,
       0.84951424, 0.80352748, 0.78189369, 0.29549508, 0.79984104,
       0.80557683, 0.75118592, 0.81900329, 0.91304359, 0.79272342,
       0.89438081, 0.8881667 , 0.91373019, 0.        , 0.81843126,
       0.        , 0.736601  , 0.87164956, 0.87118425, 0.88396476,
       0.76385709, 0.82297937, 0.67957662, 0.82755802, 0.82602603,
       0.        , 0.82334761, 0.86429772, 0.80070915, 0.84591988,
       0.36266297, 0.8419058 , 0.74848492, 0.89928028, 0.79217999,
       0.79159075, 0.79703351, 0.26284648, 0.85511197, 0.86266998,
       0.81390607, 0.4327999 , 0.86182412, 0.39608753, 0.81958023,
       0.77799877, 0.74030354, 0.91100637, 0.49508333, 0.7875859 ,
       0.73475576, 0.68127933, 0.77681764, 0.86046068, 0.     

In [14]:
(unmasked_fraction > 0.6) == (original_efeds['unmasked_fraction'] > 0.6)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [15]:
new_efeds = original_efeds.copy()
new_efeds['unmasked_area'] = all_umarea
new_efeds['galaxy_index'] = galaxy_index
new_efeds['unmasked_fraction'] = unmasked_fraction

In [16]:
new_efeds.write('data/modified_efeds_ver10.fits', overwrite=True)